[package]
name = "strategy-lph"
version.workspace = true
edition.workspace = true

[lib]
name = "lph"
path = "src/lib.rs"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
clients-binance.workspace = true
clients-uniswapv3.workspace = true
serde = { workspace = true }
