[package]
name = "close-sell"
version.workspace = true
edition.workspace = true

[[bin]]
name = "close-sell"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clients-binance.workspace = true
reqwest.workspace = true
tokio.workspace = true
