[package]
name = "clients-uniswapv3"
version.workspace = true
edition.workspace = true

[lib]
name = "clients_uniswapv3"
path = "src/lib.rs"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
serde = { workspace = true }
tokio.workspace = true
