[package]
name = "uniswapv3"
version.workspace = true
edition.workspace = true

[lib]
name = "uniswapv3"
path = "src/lib.rs"

[dependencies]
alloy = { version = "1.6", features = ["contract", "eips"] }
anyhow = "1.0"
tokio.workspace = true
